django_projects/mysite/ads/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from . import views


app_name = "ads"
urlpatterns = [
    path("", views.AdListView.as_view(), name="all"),
    path(
        "ad/<int:pk>",
        views.AdDetailView.as_view(),
        name="ad_detail",
    ),
    path(
        "ad/create",
        views.AdCreateView.as_view(success_url=reverse_lazy("ads:all")),
        name="ad_create",
    ),
    path(
        "ad/<int:pk>/update",
        views.AdUpdateView.as_view(success_url=reverse_lazy("ads:all")),
        name="ad_update",
    ),
    path(
        "ad/<int:pk>/delete",
        views.AdDeleteView.as_view(success_url=reverse_lazy("ads:all")),
        name="ad_delete",
    ),
    path("pic_picture/<int:pk>", views.stream_file, name="pic_picture"),
    path(
        "ad/<int:pk>/comment",
        views.CommentCreateView.as_view(),
        name="ad_comment_create",
    ),
    path(
        "comment/<int:pk>/comment",
        views.CommentDeleteView.as_view(success_url=reverse_lazy("ads:all")),
        name="ad_comment_delete",
    ),
    path("ad/<int:pk>/favorite", views.AddFavoriteView.as_view(), name="ad_favorite"),
    path(
        "ad/<int:pk>/unfavorite",
        views.DeleteFavoriteView.as_view(),
        name="ad_unfavorite",
    ),
]

django_projects/mysite/mysite/urls.py
import os

from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

# ? Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, "site")


# ? You should always use include() when you include other URL patterns. admin.site.urls is the only exception to this.
urlpatterns = [
    # ? admin dashboard
    path("admin/", admin.site.urls),
    # ? for user authentication
    path("accounts/", include("django.contrib.auth.urls")),
    # ? for social logins
    url(r"^oauth/", include("social_django.urls", namespace="social")),
    # ? home
    path("", include("home.urls")),
    # ?installed apps
    path("hello/", include("hello.urls")),
    path("polls/", include("polls.urls")),
    path("autos/", include("autos.urls")),
    path("cats/", include("cats.urls")),
    path("ads/", include("ads.urls")),
    path("homework/", include("homework.urls")),
    # ? for static sites
    url(
        r"^site/(?P<path>.*)$",
        serve,
        {"document_root": SITE_ROOT, "show_indexes": True},
        name="site_path",
    ),
    # ? for favicons
    path(
        "favicon.ico",
        serve,
        {"path": "favicon.ico", "document_root": os.path.join(BASE_DIR, "home/static")},
    ),
]

# ? use social logins if configured
try:
    from . import github_settings

    social_login = "registration/login_social.html"
    urlpatterns.insert(
        0,
        path(
            "accounts/login/", auth_views.LoginView.as_view(template_name=social_login)
        ),
    )
except Exception as e:
    print(
        f"------------\nSOCIAL LOGINS ERROR\n{e}\nUsing the default login template\n------------"
    )

django_projects/mysite/ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings

from taggit.managers import TaggableManager

# Create your models here.


class Ad(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    title = models.CharField(
        max_length=200,
        validators=[
            MinLengthValidator(
                2,
                "Title must be greater than 2 characters",
            )
        ],
    )
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        null=True,
    )
    text = models.TextField()

    # ? auto-generated
    owner = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(
        max_length=256, null=True, help_text="the MIME_TYPE of the file"
    )

    comments = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL,
        through="Comment",
        related_name="comments_owner",
    )

    favorites = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL,
        through="Favorite",
        related_name="favorite_ads",
    )

    tags=TaggableManager(blank=True)

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    text = models.TextField(
        validators=[
            MinLengthValidator(
                limit_value=3,
                message="Comment must be greater than 3 characters",
            )
        ]
    )

    ad = models.ForeignKey(to=Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        if len(self.text) < 15:
            return self.text
        else:
            return f"{self.text[:11]} ..."


class Favorite(models.Model):
    ad = models.ForeignKey(to=Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="favorites_users",
    )

    class Meta:
        unique_together = ["ad", "user"]  # ? only one combination

    def __str__(self) -> str:
        return f"{self.user.username} likes {self.ad.title[:10]}"

django_projects/mysite/ads/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile

from ads.humanize import natural_size
from ads.models import Ad


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = natural_size(max_upload_limit)

    picture = forms.FileField(
        required=False,
        label=f"File to upload <= {max_upload_limit_text}",
    )
    upload_field_name = "picture"

    class Meta:
        model = Ad
        fields = [
            "title",
            "text",
            "picture",
            "price",
            "tags"
        ]

    def clean(self):
        """
        inherited from the parent class
        We add further validation to it
        """

        # ? returns a mapping that has picture data
        cleaned_data = super().clean()
        if cleaned_data is None or cleaned_data.get("picture") is None:
            return None

        else:
            picture = cleaned_data.get("picture")

            if len(picture) > self.max_upload_limit:
                self.add_error(
                    field="picture",
                    error=f"File must be < {self.max_upload_limit_text} bytes",
                )

    def save(self, commit: bool = True):
        instance = super(CreateForm, self).save(commit=False)
        picture_in_memory = instance.picture

        # ? extracting data
        if isinstance(picture_in_memory, InMemoryUploadedFile):
            byte_array = picture_in_memory.read()
            instance.picture = byte_array
            instance.content_type = picture_in_memory.content_type

        if commit:
            instance.save()
            self.save_m2m()

        return instance


class CommentForm(forms.Form):
    comment = forms.CharField(
        required=True,
        max_length=500,
        min_length=3,
        strip=True,
    )

django_projects/mysite/ads/views.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.utils import IntegrityError
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from ads.models import Ad, Comment, Favorite
from ads.owner import (
    OwnerListView,
    OwnerDetailView,
    OwnerDeleteView,
)
from ads.forms import CommentForm, CreateForm
from ads.utils import generate_search_query

# Create your views here.
class AdListView(OwnerListView):
    model = Ad
    template_name = "ads/ad_list.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        search_value = request.GET.get("search", False)

        if not search_value:
            ads = Ad.objects.all().order_by("-updated_at")[:10]
        else:
            query = generate_search_query(search_value=search_value)
            ads = (
                Ad.objects.filter(query)
                .select_related()
                .distinct()
                .order_by("-updated_at")[:10]
            )

        for ad in ads:
            ad.natural_updated = naturaltime(value=ad.updated_at)

        favorites = []
        if request.user.is_authenticated:
            # ? rows=[{"id":2},...]
            rows = request.user.favorite_ads.values("id")
            # ?favorites=[2,...]
            favorites = [row["id"] for row in rows]

        context = {"ads": ads, "favorites": favorites}

        return render(
            request=request,
            template_name=self.template_name,
            context=context,
        )


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/ad_detail.html"

    def get(self, request: HttpRequest, pk: int) -> HttpResponse:
        ad = get_object_or_404(klass=self.model, id=pk)
        comments = Comment.objects.filter(ad=ad).order_by("-updated_at")

        comment_form = CommentForm()
        context = {
            "ad": ad,
            "comments": comments,
            "comment_form": comment_form,
        }

        return render(
            request=request,
            template_name=self.template_name,
            context=context,
        )


class AdCreateView(LoginRequiredMixin, View):
    template_name = "ads/ad_form.html"
    success_url = reverse_lazy("ads:all")

    def get(self, request: HttpRequest, pk=None) -> HttpResponse:
        form = CreateForm()
        context = {"form": form}

        return render(
            request=request,
            template_name=self.template_name,
            context=context,
        )

    def post(self, request: HttpRequest, pk=None) -> HttpResponse:
        form = CreateForm(
            data=request.POST,
            files=request.FILES or None,
        )

        if not form.is_valid():
            context = {"form": form}
            return render(
                request=request,
                template_name=self.template_name,
                context=context,
            )

        else:
            ad = form.save(commit=False)
            ad.owner = self.request.user
            ad.save()
            form.save_m2m()

            return redirect(to=self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = "ads/ad_form.html"
    success_url = reverse_lazy("ads:all")

    def get(self, request: HttpRequest, pk) -> HttpResponse:
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        context = {"form": form}

        return render(
            request=request,
            template_name=self.template_name,
            context=context,
        )

    def post(self, request: HttpRequest, pk) -> HttpResponse:
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(data=request.POST, files=request.FILES, instance=ad)

        if not form.is_valid():
            context = {"form": form}
            return render(
                request=request,
                template_name=self.template_name,
                context=context,
            )

        ad = form.save(commit=False)
        form.save_m2m()

        return redirect(to=self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad


def stream_file(request: HttpRequest, pk: int) -> HttpResponse:
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response["Content-Type"] = ad.content_type
    response["Content-Length"] = len(ad.picture)
    response.write(ad.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, pk: int):
        ad = get_object_or_404(klass=Ad, id=pk)

        comment = Comment(text=request.POST["comment"], owner=request.user, ad=ad)
        comment.save()

        return redirect(to=reverse_lazy("ads:ad_detail", args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    def get_success_url(self) -> str:
        ad = self.object.ad
        return reverse_lazy("ads:ad_detail", args=[ad.id])


@method_decorator(csrf_exempt, name="dispatch")
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        print(f"Add PK {pk}")

        ad = get_object_or_404(klass=Ad, id=pk)
        favorite = Favorite(user=request.user, ad=ad)

        try:
            favorite.save()
        except IntegrityError as e:
            pass

        return HttpResponse()


@method_decorator(csrf_exempt, name="dispatch")
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        print(f"Delete PK {pk}")

        ad = get_object_or_404(klass=Ad, id=pk)

        try:
            favorite = Favorite.objects.get(user=request.user, ad=ad).delete()
        except Favorite.DoesNotExist as e:
            pass

        return HttpResponse()

django_projects/mysite/ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Ad</h1>

<p>Are you sure you want to delete the ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

django_projects/mysite/ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<style>
    .overlay{
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 10;
        display: none;
        background-color: rgba(0,0,0,0.5);
}
</style>
{% endblock head %}

{% block content %}
{% if ad.content_type %}
<div id="overlay" class="overlay" style="text-align: center;" onclick="document.getElementById('overlay').style.display = 'none';" >

<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:pic_picture' ad.id %}">
</div>
{% endif %}

<span style="float: right;">

({{ ad.updated_at|naturaltime }})

{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>

<h1>{{ ad.title }}</h1>

<img style="float:right; max-width:30%;" src="{% url 'ads:pic_picture' ad.id %}" onclick="document.getElementById('overlay').style.display='block'">

<p>
{{ ad.text }}
</p>

<p>
${{ad.price}}
</p>

{% if ad.tags.all %}
<p>Tags:
    {% for tag in ad.tags.all %}
    <span style="border: 1px grey solid; background-color: LightGreen;">{{ tag }}</span>
    {% endfor %}
</p>
{% endif %}

<p>
    ({{ ad.updated_at|naturaltime }})
</p>

{% if user.is_authenticated %}
<br clear="all">

<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="All Forums" onclick="window.locatoin.href='{% url 'ads:all' %}'; return false;">
</form>
</p>
{% endif %}

{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})

{% if user == comment.owner %}
<a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}

</p>
{% endfor %}

<p>
<a href="{% url 'ads:all' %}">All ads</a>
</p>
{% endblock %}

django_projects/mysite/ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form action="" method="post" enctype="multipart/form-data" id="upload_form">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit" />
  <input
    type="submit"
    value="Cancel"
    onclick="window.location.href='{% url 'ads:all' %}';return false;"
  />
</form>

<script>
  $("#upload_form").submit(function() {
    console.log('Checking file size');
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
        if (file && file.size > {{ form.max_upload_limit }} ) {
            alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
        return false;
      }
    }
  });
  </script>
{% endblock %}

django_projects/mysite/ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block content %}
<h1>Ads</h1>

<div style="float: right">
  <form>
    <input type="text" name="search" placeholder="Search..."
    {% if search %} value="{{ search }}" {% endif %}
    >

    <button type="submit"><i class="fa fa-search"></i></button>

    <a href="{% url 'ads:all' %}"><i class="fa fa-undo"></i></a>
  </form>
</div>

<p>
{% if ads %}
<ul>
  {% for ad in ads %}
    <li>
        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
        {% if ad.owner == user %}
        (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
        <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
        <br>
        {% endif %}

        <div style="left: 10px">
          {% if ad.text|length < 100 %}
            {{ ad.text }}
          {% else %}
            {{ ad.text|slice:"0:99" }}
            <a href="{% url 'ads:ad_detail' ad.id %}">...</a>
          {% endif %}
        </div>

        <small>
          {% if ad.owner.username %}
            posted by {{ ad.owner.username }}
          {% endif %}

          {{ ad.natural_updated }}
        </small>

        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{ad.id}}">

        <span class="fa-stack" style="vertical-align: middle;">
          <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
          <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>


        <!-- the second href -->
        <a href="#" onclick=
              "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
            {% if ad.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{ad.id}}">

          <span class="fa-stack" style="vertical-align: middle;">

            <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
            <i class="fa fa-star-o fa-stack-1x"></i>
          </span>
        </a>
        {% endif %}
    </li>

  {% endfor %}
</ul>

{% else %}
  <p>There are no ads in the database.</p>
{% endif %}
</p>

<p>
<a href="{% url 'ads:ad_create' %}">Add an Ad</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>

{% else %}
<a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
{% endif %}
</p>

<script>
  function favPost(url, ad_id) {
      console.log('Requesting JSON');
      $.post(url, {},  function(rowz){
          console.log(url, 'finished');
          $("#unfavorite_star_"+ad_id).toggle();
          $("#favorite_star_"+ad_id).toggle();
      }).fail(function(xhr) {
          alert('Url failed with '+xhr.status+' '+url);
      });
  }
  </script>
{% endblock %}

django_projects/mysite/ads/templates/ads/comment_delete.html
{% extends 'base_bootstrap.html' %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete?</p>
<p>{{ comment.text }}</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." class="btn btn-primary">
    <a class="btn btn-primary" href="{% url 'ads:ad_detail' comment.ad.id %}">Cancel</a>
</form>
{% endblock content %}